create table if not exists public.waitlist_signups (
  id bigint generated by default as identity primary key,
  full_name text not null,
  email text not null,
  company_name text not null,
  role text default '',
  monthly_clients text default '',
  biggest_bottleneck text default '',
  created_at timestamptz not null default now()
);

create unique index if not exists waitlist_signups_email_unique_idx
  on public.waitlist_signups (lower(email));

alter table public.waitlist_signups enable row level security;

drop policy if exists "anon_insert_waitlist_signups" on public.waitlist_signups;
create policy "anon_insert_waitlist_signups"
  on public.waitlist_signups
  for insert
  to anon
  with check (true);

drop policy if exists "authenticated_select_waitlist_signups" on public.waitlist_signups;
create policy "authenticated_select_waitlist_signups"
  on public.waitlist_signups
  for select
  to authenticated
  using (true);
